### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by wwei4949**

### CODE REVIEW

**Comment by jdlane** [comment]
I'm not sure if I'm missing something, but I can't figure out how to render your component. How did you guys test it during development?

**Comment by wwei4949** [comment]
Wrap the <NavBar/> with BrowserRouter like so:
<BrowserRouter>
    <Navbar />
</BrowserRouter>

**Comment by jdlane** [comment]
Sorry for the delay on reviewing this. It looks like the navbar is missing the logo in the top-left that's in the designs. It also needs the ability to have a title in the navbar which should probably be a prop for the component. The designs also show that navbar links get highlighted in blue when the user is on that page, so there should also be a prop to control that. 

Last thing, maybe include the BrowserRouter tag within the navbar component if possible so that it isn't needed everytime the navbar is included in a page.

I know that this sprint is almost over, so if this is too much to get done we can always push it to the next sprint

**Comment by wwei4949** [comment]
fixed navbar

**Review by jdlane — APPROVED** [review]

**Pull request merged**
