### PR TITLE
Created settings page for admins and mentors/tutors

### PR DESCRIPTION
**Pull request by vikasreddy85**
Created admin settings page and mentor/tutor settings page.
There is a problem with the navbar since I do not know how to import it from another branch.

### CODE REVIEW

**Review by jdlane — CHANGES_REQUESTED** [review]
1. The page needs to be broken down into React components rather than one big HTML chunk. This will save us a lot of time in the future when reusing designs
2. Creating the navbar is a separate task that is being worked on by Luke and Wenjie, since it will be used on multiple pages. This means that you can delete that part from your code
3. The page is not very responsive, try to use more flex components. On my screen size it looks great at 75-80% zoom, but at 100% elements are being cut off or overlapped.

Don't hesitate to reach out with any questions

**Comment by vikasreddy85** [comment]
1. Updated settings page to be more responsive. 
2. Created React components (Reset Button, Input Form, Profile Card)

**Comment by jdlane** [comment]
Looks good! Last thing would be to get rid of the non-functional scroll bars on the boxes

**Comment by vikasreddy85** [comment]
There are no scroll bars for the boxes on my screen, but I made overflow to hidden in case other users are experiencing scroll bars on the boxes.

**Comment by jdlane** [comment]
It looks like there are some merge conflicts that have to be resolved before merging. You can run git rebase from the branch to see the differences and resolve them.

**Review by jdlane — APPROVED** [review]

**Pull request merged**
